# Configuration documentation:
#  https://embarkstudios.github.io/cargo-deny/index.html

[advisories]
version = 2
yanked = "deny"
ignore = [
  # paste is unmaintained but does not have any known issues;
  # there is no replacement at this time
  "RUSTSEC-2024-0436",
]
git-fetch-with-cli = true

[licenses]
unused-allowed-license = "deny"
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]

[[licenses.clarify]]
name = "ring"
expression = "BSD-4-Clause AND ISC AND MIT AND OpenSSL"
license-files = [
  # https://github.com/briansmith/ring/blob/95948b3977013aed16db92ae32e6b8384496a740/LICENSE
  { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true
deny = [
  # We are using rustls as the TLS implementation, so we shouldn't be linking
  # in OpenSSL too.
  #
  # If you're hitting this, you might want to take a look at what new
  # dependencies you have introduced and check if there's a way to depend on
  # rustls instead of OpenSSL (tip: check the crate's feature flags).
  { name = "openssl-sys" },
  # Use stdlib ( https://doc.rust-lang.org/stable/std/io/trait.IsTerminal.html )
  { name = "atty" },
]

[sources]
unknown-git = "deny"
required-git-spec = "rev"
unused-allowed-source = "deny"

[sources.allow-org]
github = [
  "influxdata",
]
