[package]
name = "datafusion-udf-wasm-arrow2bytes"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow.workspace = true

[dev-dependencies]
arrow = { workspace = true, features = ["ipc_compression"] }
insta.workspace = true

[lints]
workspace = true
